modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="liu_new_recipes"
version="1.1"
displayName="Liu's New Recipes"
displayURL="https://www.mcmod.cn/class/28362.html"
logoFile="logo.png"
credits="By Lxh2014"
authors="Lxh2014"
description="This mod adds 26.2 recipes and some items required for Forge/Fabric 1.20.1 (currently only copper tools and equipment). This allows you to play some 26.2 content directly from version 1.20.1 without downloading the higher version 26.2."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.liu_new_recipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration